# Generated by Django 3.2.4 on 2021-06-21 12:00

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateTimeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('edited_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('is_student', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='About',
            fields=[
                ('datetimemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='schoolApp.datetimemodel')),
                ('aboutTitle', models.CharField(max_length=250)),
                ('aboutDexcription1', models.TextField()),
                ('aboutDexcription2', models.TextField()),
            ],
            bases=('schoolApp.datetimemodel',),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('datetimemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='schoolApp.datetimemodel')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=250)),
                ('message', models.TextField()),
            ],
            bases=('schoolApp.datetimemodel',),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('datetimemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='schoolApp.datetimemodel')),
                ('courseName', models.CharField(max_length=250)),
                ('coureseBy', models.CharField(max_length=250)),
                ('CourseDescription', models.TextField()),
                ('courseImage', models.ImageField(upload_to='')),
            ],
            bases=('schoolApp.datetimemodel',),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('datetimemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='schoolApp.datetimemodel')),
                ('eventTitle', models.CharField(max_length=250)),
                ('eventDescription', models.TextField()),
                ('eventBy', models.CharField(max_length=250)),
                ('eventAt', models.DateTimeField()),
            ],
            bases=('schoolApp.datetimemodel',),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('datetimemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='schoolApp.datetimemodel')),
                ('serviceTitile', models.CharField(max_length=250)),
                ('serviceDescription', models.TextField()),
            ],
            bases=('schoolApp.datetimemodel',),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('datetimemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='schoolApp.datetimemodel')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('mobile', models.CharField(max_length=250)),
                ('message', models.TextField()),
            ],
            bases=('schoolApp.datetimemodel',),
        ),
    ]
